# Pi-hole + Unbound Docker Compose Configuration
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Unbound info at https://unbound.docs.nlnetlabs.nl/
services:

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    environment:
      TZ: ${TZ}
    volumes:
      - './data/unbound/config:/opt/unbound/etc/unbound/'
      - './data/unbound/logs:/opt/unbound/var/log'
    healthcheck:
      test: ['CMD', 'drill-hc', '@127.0.0.1', 'dnssec.works']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      unbound:
        condition: service_healthy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "123:123/udp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: 'unbound#53;8.8.8.8;1.1.1.1'
      FTLCONF_dns_dnssec: 'false'
      FTLCONF_dns_rateLimit_count: '0'
      FTLCONF_dns_rateLimit_interval: '0'
    volumes:
      - './data/pihole:/etc/pihole'
      - ./data/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pihole-exporter:
    build:
      context: ./pihole6-exporter
    container_name: pihole-exporter
    hostname: pihole-exporter
    depends_on:
      pihole:
        condition: service_started
    ports:
      - "9666:9666"
    environment:
      - TZ=${TZ}
      - PIHOLE_APP_PASSWORD=${PIHOLE_APP_PASSWORD}
    command:
      - pihole6_exporter
      - -H
      - pihole
      - -k
      - ${PIHOLE_APP_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://192.168.15.22:9666/metrics"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    external: true
    name: pihole-unbound_backend
