services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./data/nextcloud/html:/var/www/html
      - ./data/nextcloud/custom_apps:/var/www/html/custom_apps
      - ./data/nextcloud/config:/var/www/html/config
      - ./data/nextcloud/data:/var/www/html/data
      - ./data/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
      - TZ=${TZ}
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nextcloud-exporter:
    image: xperimental/nextcloud-exporter:latest
    container_name: nextcloud-exporter
    hostname: nextcloud-exporter
    restart: unless-stopped
    depends_on:
      nextcloud:
        condition: service_healthy
    ports:
      - "9205:9205"
    environment:
      - TZ=${TZ}
      - NEXTCLOUD_SERVER=http://192.168.15.22:8080
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TIMEOUT=5s
      - LISTEN_ADDR=:9205
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9205/metrics"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # collabora:
  #   image: collabora/code:latest
  #   container_name: collabora
  #   restart: unless-stopped
  #   environment:
  #     - TZ=${TZ}
  #     - password=${COLLABORA_PASSWORD}
  #     - username=nextcloud
  #     - aliasgroup1=http://192.168.15.22:8080
  #     - aliasgroup2=https://nextcloud.caduveloso.com
  #     - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false --o:user_interface.mode=notebookbar
  #     - dictionaries=en_US pt_BR
  #   ports:
  #     - "9980:9980"
