services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - DEFAULT_THEME=dark
    ports:
      - "8085:8081"
    volumes:
      - /data/metube/downloads:/downloads

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - "8086:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /data/qbittorrent/config:/config
      - /data/qbittorrent/downloads:/downloads
